In [1]:
import statistics

data = [10, 20, 20, 30, 40, 100]

print(statistics.mean(data))   
print(statistics.median(data)) 
print(statistics.mode(data))

36.666666666666664
25.0
20

In [ ]:
import statistics
import numpy as np

data = [10, 20, 20, 30, 40, 100]

print(statistics.variance(data))        
print(statistics.stdev(data))           
print(np.percentile(data, 75) -
      np.percentile(data, 25))

1066.6666666666667
32.65986323710904
17.5

In [3]:
import pandas as pd

df = pd.DataFrame({
    "age":    [22, 25, 30, 35, 28, 40, 60],
    "salary": [30000, 45000, 52000, 61000, 48000, 75000, 120000]
})

df.describe()

             age         salary
count   7.000000       7.000000
mean   34.285714   61571.428571
std    12.841525   29273.749007
min    22.000000   30000.000000
25%    26.500000   46500.000000
50%    30.000000   52000.000000
75%    37.500000   68000.000000
max    60.000000  120000.000000

In [5]:
from scipy import stats

data = [10, 20, 20, 30, 40, 100]
print(stats.skew(data))

1.4185056232264295

In [6]:
print(np.var(data))

888.8888888888888

In [7]:
import pandas as pd

df = pd.read_csv("car_data.csv")
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [8]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [9]:
df = df.dropna()  # simple case

In [10]:
print("Mean:\n", df.mean(numeric_only=True))
print("Median:\n", df.median(numeric_only=True))
print("Std:\n", df.std(numeric_only=True))

Mean:
 Series([], dtype: float64)
Median:
 Series([], dtype: float64)
Std:
 Series([], dtype: float64)

In [12]:
from scipy import stats

data = [45, 50, 55, 60, 52]

t_stat, p_value = stats.ttest_1samp(data, 50)

print(p_value)

0.39176190830174107